- build.gradle
- cognito-pre-token-generation/src/main/java/no/unit/nva/cognito/service/CustomerApiClient.java
- cognito-pre-token-generation/src/main/java/no/unit/nva/cognito/service/UserApiClient.java
- cognito-pre-token-generation/src/test/java/no/unit/nva/cognito/service/CustomerApiClientTest.java
- cognito-pre-token-generation/src/test/java/no/unit/nva/cognito/service/UserApiClientTest.java
- customer-commons/build.gradle
- template.yaml
- user-access-handlers/src/test/java/no/unit/nva/handlers/GetRoleHandlerTest.java
https://unit.atlassian.net/browse/NP-2711
> Sending in service base url with suffix to trigger

- cognito-pre-token-generation/src/main/java/no/unit/nva/cognito/TriggerHandler.java
- cognito-pre-token-generation/src/test/java/no/unit/nva/cognito/TriggerHandlerTest.java
AWS Cognito's property 'custom:hostedAffiliation' is read with URLDecoding before being used.
> URLDecoding hosted user affiliation

- cognito-pre-token-generation/src/main/java/no/unit/nva/cognito/TriggerHandler.java
- cognito-pre-token-generation/src/main/java/no/unit/nva/cognito/service/UserDetails.java
- cognito-pre-token-generation/src/main/java/no/unit/nva/cognito/service/UserPoolEntryUpdater.java
- cognito-pre-token-generation/src/test/java/no/unit/nva/cognito/TriggerHandlerTest.java
- customer-testing/src/main/java/no/unit/nva/customer/testing/TestHeaders.java
Continuing my effort to separate the logic of creating the update request to Cognito in an own class. In this PR, I moved the generation of the attributes in the UserPoolEntryUpdater class
> Np 3066 move more logic to separate user pool handler

- docs/customer-swagger.yaml
- docs/users-and-roles-swagger.yaml
- OpenApi 3.x
- Handle application/ld+json as media type
- Better examples
> Np2579 Update OpenApi Spec to version 3.x

- template.yaml
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-refreshtokenvalidity
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-tokenvalidityunits
> Setting RefreshTokenValidity to 1 hour

- cognito-pre-token-generation/build.gradle
- cognito-pre-token-generation/src/test/java/no/unit/nva/cognito/TriggerHandlerTest.java
- customer-commons/src/test/java/no/unit/nva/customer/model/CustomerTest.java
- customer-commons/src/test/java/no/unit/nva/customer/service/impl/DynamoDBCustomerServiceTest.java
- customer-testing/src/main/java/no/unit/nva/customer/testing/CustomerDataGenerator.java
- customer/build.gradle
- customer/src/test/java/no/unit/nva/customer/get/GetCustomerByCristinIdHandlerTest.java
- template.yaml
- user-access-commons/build.gradle
- user-access-commons/src/main/java/no/unit/nva/useraccessmanagement/constants/ServiceConstants.java
- user-access-commons/src/main/java/no/unit/nva/useraccessmanagement/model/ViewingScope.java
- user-access-commons/src/test/java/no/unit/nva/useraccessmanagement/model/ViewingScopeTest.java
- user-access-handlers/build.gradle
- user-access-handlers/src/test/java/no/unit/nva/handlers/UpdateUserHandlerTest.java
- user-access-handlers/src/test/java/no/unit/nva/handlers/UpdateViewingScopeHandlerTest.java
- user-access-internal-model/build.gradle
- user-access-internal-model/src/test/java/no/unit/nva/useraccessmanagement/dao/DynamoEntryWithRangeKeyTest.java
- user-access-internal-model/src/test/java/no/unit/nva/useraccessmanagement/dao/EntityUtils.java
- user-access-internal-model/src/test/java/no/unit/nva/useraccessmanagement/dao/UserDbTest.java
- user-access-public-model/build.gradle
- user-access-public-model/src/main/java/no/unit/nva/useraccessmanagement/model/UserDto.java
- user-access-public-model/src/test/java/no/unit/nva/useraccessmanagement/model/EntityUtils.java
- user-access-public-model/src/test/java/no/unit/nva/useraccessmanagement/model/UserDtoTest.java
- user-access-service/build.gradle
- user-access-service/src/test/java/no/unit/nva/database/DatabaseServiceTest.java
- user-access-testing/build.gradle
- user-access-testing/src/main/java/no/unit/nva/RandomUserDataGenerator.java
Validation for URIs submitted to ViewingScope. For now, the only check is that they should be URIs that start with 
`https://api.{env}.nva.aws.unit.no/cristin`
> NP-3015:validate ViewingScope URIs

- user-access-commons/src/main/java/no/unit/nva/useraccessmanagement/interfaces/WithType.java
- user-access-event-handlers/build.gradle
- user-access-event-handlers/src/main/java/no/unit/nva/useraccess/events/EventBasedScanHandler.java
- user-access-event-handlers/src/main/java/no/unit/nva/useraccess/events/MigrationService.java
- user-access-event-handlers/src/test/java/no/unit/nva/useraccess/events/EventBasedScanHandlerTest.java
EventBasedScanHandler scans one page of database entries and applies the migration action.
Expected functionality: to migrate at least one user.
Most of the functionality will be moved to IdentityService
> Np 3544 eventbasedhandler processes migrates an entry.

- template.yaml
Application client for testing
> testing client

- cognito-pre-token-generation-openid/src/main/java/no/unit/nva/cognito/CustomerAccessRight.java
- cognito-pre-token-generation-openid/src/main/java/no/unit/nva/cognito/UserSelectionUponLoginHandler.java
- cognito-pre-token-generation-openid/src/test/java/no/unit/nva/cognito/UserSelectionUponLoginHandlerTest.java
- gradle/libs.versions.toml
When a Person is connected to exactly one Customer then we add the Customer Id in the Cognito Groups.
> Inject customer id in congito groups

- cognito-pre-token-generation-openid/build.gradle
Added zalando problem library to pre-token-trigger
> added zalando to token trigger

- template.yaml
re-enable live alias for pre-token-trigger in template
> re-enable live alias for pre-token-trigger

- cognito-pre-token-generation-openid/src/main/java/no/unit/nva/cognito/CustomerAccessRight.java
- cognito-pre-token-generation-openid/src/test/java/no/unit/nva/cognito/NvaDataGenerator.java
- cognito-pre-token-generation-openid/src/test/java/no/unit/nva/cognito/UserSelectionUponLoginHandlerTest.java
- user-access-handlers/src/main/java/no/unit/nva/handlers/IdentityServiceInitHandler.java
- user-access-handlers/src/main/java/no/unit/nva/handlers/models/RoleList.java
- user-access-handlers/src/test/java/no/unit/nva/handlers/EntityUtils.java
- user-access-handlers/src/test/java/no/unit/nva/handlers/IdentityServiceInitHandlerTest.java
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/dao/AccessRightSetConverter.java
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/dao/AccessRightSetConverterProvider.java
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/dao/RoleDb.java
- user-access-internal-model/src/test/java/no/unit/nva/useraccessservice/dao/EntityUtils.java
- user-access-public-model/src/main/java/no/unit/nva/useraccessservice/model/RoleDto.java
- user-access-public-model/src/main/java/no/unit/nva/useraccessservice/model/UserDto.java
- user-access-public-model/src/test/java/no/unit/nva/useraccessservice/model/EntityUtils.java
- user-access-public-model/src/test/java/no/unit/nva/useraccessservice/model/RoleDtoTest.java
- user-access-public-model/src/test/java/no/unit/nva/useraccessservice/model/UserDtoTest.java
- user-access-service/src/main/java/no/unit/nva/database/RoleService.java
- user-access-service/src/test/java/no/unit/nva/database/EntityUtils.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/UserEntriesCreatorForPerson.java
This is a bit of two PRs in one. One PR is the creation of a handler for initialiazing the default roles. The other one is using a Set of AccessRights everywhere instead of List of Strings or List of AccessRights
> NP-9098: handler for initializing default roles

- template.yaml
> NP9312-Create-app-client-for-DLR, client created

- template.yaml
> NP9312-Create-app-client-for-DLR, code review

- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/cristin/CristinPersonRegistry.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/cristin/model/CristinAffiliationInstitution.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/cristin/model/PersonSearchResultItem.java
- Moved some of the common functionality into methods
- Interrupted the execution before throwing
> Refactoring suggestion

- template.yaml
something was still commented out in template
> added missing provisioned concurrency setting

- cognito-pre-token-generation-openid/src/main/resources/log4j2.xml
- template.yaml
To be merged when we have verified that identity service is stable in all environments including production.
> enabled provisioned concurrency and reset logging level back to info

- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/AuthenticationScenarios.java
- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/MockPersonRegistry.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/cristin/model/CristinPerson.java
- user-creation/src/test/java/no/unit/nva/useraccessservice/usercreation/CristinPersonRegistryTest.java
Cristin do not serialize empty arrays, so I made sure to handle that in deserialization.
> fixed NullPointerException for Crisin persons without affiliations

- customer-commons/src/main/java/no/unit/nva/customer/model/SecretManagerDoiAgentDao.java
- customer-commons/src/test/java/no/unit/nva/customer/model/SecretManagerDoiAgentDaoTest.java
- customer/src/main/java/no/unit/nva/customer/CustomerDoiHandler.java
- customer/src/main/java/no/unit/nva/customer/update/UpdateCustomerDoiHandler.java
- customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerDoiHandlerTest.java
> #NP-44745 doi update with duplicates

- customer-commons/src/main/java/no/unit/nva/customer/model/Sector.java
[NP-44827](https://unit.atlassian.net/browse/NP-44827): Added Sector enum value OTHER
[NP-44827]: https://unit.atlassian.net/browse/NP-44827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added Sector enum value OTHER

- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerDao.java
- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerDto.java
- customer-commons/src/test/java/no/unit/nva/customer/model/CustomerDaoTest.java
- customer-commons/src/test/java/no/unit/nva/customer/model/CustomerDtoTest.java
- customer-commons/src/test/java/no/unit/nva/customer/service/impl/DynamoDBCustomerServiceTest.java
- customer-testing/src/main/java/no/unit/nva/customer/testing/CustomerDataGenerator.java
- customer/src/main/java/no/unit/nva/customer/create/CreateCustomerRequest.java
- customer/src/test/java/no/unit/nva/customer/NvaApplicationDomainHandlerTest.java
- customer/src/test/java/no/unit/nva/customer/create/CreateCustomerHandlerTest.java
- customer/src/test/java/no/unit/nva/customer/testing/CreateUpdateControlledVocabularySettingsTests.java
https://unit.atlassian.net/browse/NP-44885: Added rboInstitution field on CustomerDao, CustomerDto and CreateCustomerRequest.
> Customer rboInstitution field

- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerDto.java
Added rboInstitution field in copy method
> Added rboInstitution field in copy method

- buildSrc/src/main/groovy/nva.identity.service.java-common-conventions.gradle
- user-access-service/src/main/java/no/unit/nva/database/UserService.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/UserEntriesCreatorForPerson.java
Removed non-effective diagnostic logging and set method coverage back to 1.000
> removed non-effective diagnostic logging

- cognito-pre-token-generation-openid/src/test/java/no/unit/nva/cognito/UserSelectionUponLoginHandlerTest.java
- user-access-service/src/main/java/no/unit/nva/database/IdentityService.java
- user-access-service/src/main/java/no/unit/nva/database/IdentityServiceImpl.java
- user-access-service/src/main/java/no/unit/nva/database/RoleService.java
- user-access-service/src/test/java/no/unit/nva/database/EntityUtils.java
- user-access-service/src/test/java/no/unit/nva/database/IdentityServiceImplTest.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/UserEntriesCreatorForPerson.java
The problem was that when user was updated during login, the updated user was not used in the login logic. Now fixed.
> Np 44861 access rights

- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerDao.java
- customer-commons/src/test/java/no/unit/nva/customer/model/CustomerDaoTest.java
- customer-commons/src/test/java/no/unit/nva/customer/service/impl/DynamoDBCustomerServiceTest.java
Fixing rboInstution bug where the value was not put to the DynamoDB table.
Added new test to validate that rboInstitute value is persisted.
Fixed by recreating 
- getters
- setters
- hashcode
- equals
> NP 45375 Fix rboInstitution not mapping to schema

- template.yaml
Scope for external users for [nva-data-report-api](https://github.com/BIBSYSDEV/nva-data-report-api)
> Add scope reporting-read

- customer-commons/src/test/java/no/unit/nva/customer/model/VocabularyListTest.java
- customer/src/main/java/no/unit/nva/customer/CustomerDoiHandler.java
- customer/src/main/java/no/unit/nva/customer/WriteControlledVocabularyHandler.java
- customer/src/main/java/no/unit/nva/customer/get/GetControlledVocabularyHandler.java
- customer/src/main/java/no/unit/nva/customer/get/GetCustomerDoiHandler.java
- customer/src/main/java/no/unit/nva/customer/get/GetCustomerHandler.java
- customer/src/main/java/no/unit/nva/customer/get/ListAllCustomersHandler.java
- customer/src/main/java/no/unit/nva/customer/update/UpdateCustomerDoiHandler.java
- customer/src/main/java/no/unit/nva/customer/update/UpdateCustomerHandler.java
- customer/src/test/java/no/unit/nva/customer/get/GetControlledVocabularyHandlerTest.java
- customer/src/test/java/no/unit/nva/customer/get/GetCustomerDoiHandlerTest.java
- customer/src/test/java/no/unit/nva/customer/get/GetCustomerHandlerTest.java
- customer/src/test/java/no/unit/nva/customer/get/ListAllCustomersHandlerTest.java
- customer/src/test/java/no/unit/nva/customer/testing/CreateUpdateControlledVocabularySettingsTests.java
- customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerDoiHandlerTest.java
- customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerPublicationWorkflowTest.java
- customer/src/test/java/no/unit/nva/customer/update/UpdateCustomerHandlerTest.java
- docs/customer-swagger.yaml
- gradle/libs.versions.toml
- template.yaml
customer doi
update customer
list customers
vocabs
> restrict-api

- user-access-handlers/src/main/java/no/unit/nva/handlers/data/DefaultRoleSource.java
- user-access-handlers/src/test/java/no/unit/nva/handlers/data/DefaultRoleSourceTest.java
After merge we need to run init identityservice lambda in each enviorment
> institution admin should not have resource accessright

- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerDao.java
- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerDto.java
- customer-commons/src/test/java/no/unit/nva/customer/model/CustomerDaoTest.java
- customer-testing/src/main/java/no/unit/nva/customer/testing/CustomerDataGenerator.java
- customer/src/test/java/no/unit/nva/customer/create/CreateCustomerHandlerTest.java
Migrating/ creating new variable serviceCenter and setting serviceCenter.uri = serviceCenterUri.
After we have migrated, there will be a new pr on removing serviceCenterUri.
> migration serviceCenterUri

- cognito-pre-token-generation-openid/src/test/java/no/unit/nva/cognito/UserSelectionUponLoginHandlerTest.java
- user-access-handlers/src/main/java/no/unit/nva/handlers/CreateUserHandler.java
- user-access-handlers/src/main/java/no/unit/nva/handlers/models/CreateUserRequest.java
- user-access-handlers/src/test/java/no/unit/nva/handlers/CreateUserHandlerTest.java
- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/AuthenticationScenarios.java
- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/MockPersonRegistry.java
- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/MockedPersonData.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/PersonRegistry.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/cristin/CristinPersonRegistry.java
- user-creation/src/test/java/no/unit/nva/useraccessservice/usercreation/CristinPersonRegistryTest.java
- user-creation/src/test/java/no/unit/nva/useraccessservice/usercreation/UserEntriesCreatorForPersonTest.java
Adds a new (optional) parameter to CreateUser for "cristinIdentifier". This should be in format "1234567" (not URI).
If the new parameter is present a nin is nott needed as the identifier will be used instead to fetch the person.
We can later refactor out nin entirly after Frontend has done the switch
> Createuser cristinid

- customer/src/main/java/no/unit/nva/customer/create/CreateCustomerRequest.java
- customer/src/test/java/no/unit/nva/customer/create/CreateCustomerHandlerTest.java
- docs/customer-swagger.yaml
Trodde at customer opprettes via `CustomerDto`, men det gjør den ikke. 
- La til `generalSupportEnabled` til `CreateCustomerRequest`
- Oppdaterte swagger schema til `Customer` objektet
> adding generalSupportEnabled to CreateCustomerRequest

- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/MockPersonRegistry.java
- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/RandomNin.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/cristin/CristinPersonRegistry.java
- user-creation/src/test/java/no/unit/nva/useraccessservice/usercreation/CristinPersonRegistryTest.java
- Masks URI
- Correctly(-ish) formats the data we try to mask
> Mask logging of uri

- build.gradle
- buildSrc/src/main/groovy/nva.identity.service.dynamodblocal.gradle
- buildSrc/src/main/groovy/nva.identity.service.java-common-conventions.gradle
- gradle/wrapper/gradle-wrapper.properties
- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/MockPersonRegistry.java
- user-creation-testing/src/main/java/no/unit/nva/useraccessservice/userceation/testing/cristin/RandomNin.java
- user-creation/src/main/java/no/unit/nva/useraccessservice/usercreation/person/cristin/CristinPersonRegistry.java
- user-creation/src/test/java/no/unit/nva/useraccessservice/usercreation/CristinPersonRegistryTest.java
- Fixes deprecated gradle features
- Bumps to gradle 8.10.1
> Modernize gradle setup

- gradle/libs.versions.toml
- Bumps to latest (which hasn't been published at the time of writing)
> Bump to latest commons

- .github/workflows/gradle.yml
- template.yaml
ticket: https://sikt.atlassian.net/browse/NP-47623
> [np-47623] Add backup tags

- cognito-pre-token-generation-openid/build.gradle
- user-access-handlers/src/main/java/no/unit/nva/handlers/GetCurrentTermsConditionsHandler.java
- user-access-internal-model/build.gradle
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/dao/TermsConditions.java
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/dao/UserDao.java
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/interfaces/DataAccessClass.java
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/interfaces/DataAccessLayer.java
- user-access-internal-model/src/main/java/no/unit/nva/useraccessservice/interfaces/DataAccessService.java
- user-access-internal-model/src/test/java/no/unit/nva/useraccessservice/dao/TermsConditionsTest.java
- user-access-internal-model/src/test/java/no/unit/nva/useraccessservice/dao/UserDaoTest.java
- user-access-internal-model/src/test/java/no/unit/nva/useraccessservice/interfaces/DataAccessClassTest.java
- user-access-public-model/src/main/java/no/unit/nva/useraccessservice/model/TermsConditionsResponse.java
- user-access-public-model/src/test/java/no/unit/nva/useraccessservice/model/TermsConditionsResponseTest.java
- user-access-service/build.gradle
- user-access-service/src/main/java/no/unit/nva/database/DynamoCrudService.java
- user-access-service/src/test/java/no/unit/nva/database/DynamoCrudServiceTest.java
- user-access-service/src/test/java/no/unit/nva/database/DynamoDbTableCreator.java
- user-access-service/src/test/java/no/unit/nva/database/DynamoDbTestClientProvider.java
- user-access-service/src/test/java/no/unit/nva/database/LocalDynamoCrudTestDatabase.java
Her er hva som trengs for å bruke sdk2.
Interfacen definerer en del meta felt som ikke er en del av buisness objektene, men som er nødvendig om man skal har tilgangskontroll og litt auditing
> sdk2 DynamoDb DDD

- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerReference.java
- customer-commons/src/test/java/no/unit/nva/customer/model/CustomerReferenceTest.java
> Np 47716 serving is active param when listing customers

- customer/src/main/java/no/unit/nva/customer/get/FetchChannelClaimHandler.java
- template.yaml
Allowing internal client to fetch channel claim and adding missing environment variable to template.
> allowing backend client to fetch channel claim

- customer-commons/src/main/java/no/unit/nva/customer/model/CustomerDto.java
- customer-commons/src/main/java/no/unit/nva/customer/service/CustomerService.java
- customer-commons/src/main/java/no/unit/nva/customer/service/impl/DynamoDBCustomerService.java
- customer-commons/src/test/java/no/unit/nva/customer/service/impl/DynamoDBCustomerServiceTest.java
- customer/src/main/java/no/unit/nva/customer/RequestUtils.java
- customer/src/main/java/no/unit/nva/customer/delete/DeleteChannelClaimHandler.java
- customer/src/main/java/no/unit/nva/customer/get/DeleteChannelClaimHandler.java
- customer/src/test/java/no/unit/nva/customer/get/DeleteChannelClaimHandlerTest.java
- docs/customer-swagger.yaml
- template.yaml
Handler for deleting channel claim.
> creating delete channel claim handler

- buildspec.yaml
Changes:
- Enable S3 caching for Gradle files
- Move `sam package` step for visibility in phase details
> ci: Update buildspec

- user-access-handlers/src/main/java/no/unit/nva/handlers/CreateUserHandler.java
- user-access-handlers/src/test/java/no/unit/nva/handlers/CreateUserHandlerTest.java
When creating user
And fetching user fails (external api error/ parsing of values)
Then return BadGateway
> throwing bad gateway when failing on fetching person
